import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Image, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const C = { ink: '#19201D', muted: '#68716C', cream: '#F8F6F0', card: '#FFFFFF', green: '#215C48', greenSoft: '#E5EFEA', coral: '#F0785E', border: '#E7E5DE' };

export default function ResetDetailScreen() {
  const item = useLocalSearchParams<{ id: string; title: string; roomType: string; minutes: string; beforeUrl?: string; afterUrl?: string }>();
  const share = () => Share.share({ title: 'My Reset', message: `I completed a ${item.minutes}-minute Reset and made space to breathe. Small resets add up.`, ...(item.afterUrl ? { url: item.afterUrl } : {}) });
  return <SafeAreaView style={styles.page} edges={['top', 'bottom']}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={styles.circle}><Ionicons name="chevron-back" size={23} color={C.ink} /></Pressable><Text style={styles.headerTitle}>Your reset</Text><Pressable onPress={share} style={styles.circle}><Ionicons name="share-outline" size={22} color={C.green} /></Pressable></View>
    <View style={styles.body}><Text style={styles.eyebrow}>{item.roomType?.toUpperCase()}</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.meta}>{item.minutes} focused minutes · Completed</Text>
      <View style={styles.compare}><View style={styles.photoWrap}>{item.beforeUrl ? <Image source={{ uri: item.beforeUrl }} style={styles.photo} /> : null}<Text style={styles.badge}>BEFORE</Text></View><View style={styles.photoWrap}>{item.afterUrl ? <Image source={{ uri: item.afterUrl }} style={styles.photo} /> : <View style={styles.missing}><Ionicons name="camera-outline" size={30} color={C.green} /><Text style={styles.missingText}>Add your after photo</Text></View>}<Text style={styles.badge}>AFTER</Text></View></View>
      <Text style={styles.note}>{item.afterUrl ? 'Look at the visible difference your focused effort made.' : 'Complete the story with a photo from roughly the same angle.'}</Text>
    </View>
    <View style={styles.actions}>{!item.afterUrl ? <Pressable onPress={() => router.push({ pathname: '/camera', params: { mode: 'after', sessionId: item.id } })} style={styles.primary}><Ionicons name="camera" size={20} color="#FFFFFF" /><Text style={styles.primaryText}>Take after photo</Text></Pressable> : <Pressable onPress={share} style={styles.primary}><Ionicons name="share-outline" size={20} color="#FFFFFF" /><Text style={styles.primaryText}>Share my reset</Text></Pressable>}</View>
  </SafeAreaView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: C.cream }, header: { height: 66, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, circle: { width: 42, height: 42, borderRadius: 21, backgroundColor: C.card, borderWidth: 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center' }, headerTitle: { color: C.ink, fontSize: 15, fontWeight: '700' }, body: { flex: 1, paddingHorizontal: 20, paddingTop: 24 }, eyebrow: { color: C.coral, fontSize: 11, fontWeight: '800', letterSpacing: 1.4 }, title: { color: C.ink, fontSize: 28, fontWeight: '700', marginTop: 7 }, meta: { color: C.muted, fontSize: 14, marginTop: 7 }, compare: { flexDirection: 'row', gap: 8, marginTop: 28 }, photoWrap: { flex: 1, height: 310, borderRadius: 18, overflow: 'hidden', backgroundColor: C.greenSoft }, photo: { width: '100%', height: '100%' }, badge: { position: 'absolute', left: 10, bottom: 10, color: C.ink, backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 10, paddingHorizontal: 9, paddingVertical: 5, fontSize: 10, fontWeight: '800', overflow: 'hidden' }, missing: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 14 }, missingText: { color: C.green, fontSize: 12, fontWeight: '700', textAlign: 'center', marginTop: 8 }, note: { color: C.green, backgroundColor: C.greenSoft, borderRadius: 15, padding: 15, fontSize: 14, lineHeight: 20, textAlign: 'center', marginTop: 18 }, actions: { paddingHorizontal: 20, paddingBottom: 8 }, primary: { height: 58, borderRadius: 18, backgroundColor: C.green, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, primaryText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' } });
